### ISSUE TITLE
Replacement for this project?

### ISSUE THREAD

**Issue by szabgab** [techvision/brails#69]
As I can see the web site http://brails.org/ is not available any more and the project has not seen any changes in 3 years. Is there a recommended alternative for this project?

**Comment by sidnc86** [comment]
No. The work has stopped and this project isn't proceeding any more. We have changed our approach from a web app to basic native apps.

**Comment by szabgab** [comment]
Thanks, could you link to those projects please?

**Comment by sidnc86** [comment]
We can't as they are under development and not on github.

**Comment by szabgab** [comment]
Thanks.
